### ISSUE TITLE
problem with `settings.json` - `cannot find module`

### ISSUE THREAD

**Issue by philipp-schwemberger** [soixantecircuits/altruist#18]
While testing Altruist I filled out only the `"twitter"` section in `"actions"`. But it didn't work till I deleted all the other unused actions in the `settings.json`.
![altruist_module](https://cloud.githubusercontent.com/assets/27734882/25860521/1918fd8a-34e2-11e7-82fb-5dfcc6a4e058.png)

**Comment by negabakuru** [comment]
Should be fixed in https://github.com/soixantecircuits/altruist/commit/0e525d753e4d970f952c04e1e8cc2218b3d58073
