### ISSUE TITLE
"can not parse response" and "empty reply from server" messages

### ISSUE THREAD

**Issue by philipp-schwemberger** [soixantecircuits/altruist#21]
My very first posting on twitter via altruist took a few minutes to be sent.  
The following ones were faster. But still i get these messages on the server and client side:  
  
![tweetsfromaltruist](https://user-images.githubusercontent.com/27734882/27478972-10e10902-5812-11e7-89fc-ca4fcb996dc9.png)

**Comment by negabakuru** [comment]
This should be solved with v1.1.0
